### ISSUE TITLE
kalo ini kaya gini knp mas?

### ISSUE THREAD

**Issue by aang69** [ardzz/OtakudesuCLI#2]
PS C:\Users\Ilham Nurhidayat\OtakudesuCLI> php OtakudesuCLI.php
USAGE:
   OtakudesuCLI.php <OPTIONS> [<argument>]

   Unofficial Otakudesu Client (CLI based) mempermudah kepentingan
   nge-weaaboo di semua OS!

OPTIONS:
   -p, --install         Install OtakudesuCLI ke sistem
   -u, --uninstall       Unstall OtakudesuCLI dari sistem

   -l, --anime-list      Lihat daftar anime yang tersedia di Otakudesu

   -c, --complete-anime  Lihat daftar anime (lengkap)

   -o, --ongoing-anime   Lihat daftar anime (ongoing)

   -g, --genre-list      Lihat daftar genre anime

   -s <nama_anime>,      Cari anime
   --cari-anime
   <nama_anime>

   -i <id_anime>,        Cari informasi anime, contohnya :
   --info-anime          ogairu-season-3-sub-indo
   <id_anime>

   -v, --version         Print current version

   -h, --help            Display this help screen and exit immediately.

   --no-colors           Do not use any colors in output. Useful when
                         piping output to other tools or files.

   --loglevel <level>    Minimum level of messages to display. Default is
                         info. Valid levels are: debug, info, notice,
                         success, warning, error, critical, alert,
                         emergency.

ARGUMENTS:
   <argument>            Arguments can be required or optional. This one
                         is optional
PS C:\Users\Ilham Nurhidayat\OtakudesuCLI> sudo php OtakudesuCLI.php --install
sudo : The term 'sudo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ sudo php OtakudesuCLI.php --install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ardzz** [comment]
Halo @aang69 untuk saat ini, fitur install ke sistem hanya bisa dilakukan di Linux 😉
Untuk di Windows bisa jalankan program nya seperti biasa, tanpa install ke system
